import type React from 'react';
import type { AppThemeId, AppThemePreset } from '../types/theme';

export const appThemePresets: AppThemePreset[] = [
  {
    id: 'warm-ivory',
    label: '웜 아이보리',
    description: 'When We Meet 기본 테마',
    previewClassName: 'bg-[#F8F5F2]',
    tokens: {
      primary: '#D96B7C',
      primaryDeep: '#B94D61',
      primarySoft: '#F7DDE3',
      primaryHalo: 'rgba(217, 107, 124, 0.26)',
      bgApp: '#F8F5F2',
      surface: '#FFFFFF',
      surfaceWarm: '#FDF9F6',
      line: '#E8E1DD',
      lineStrong: '#D8CDC7',
      ink: '#191716',
      inkMuted: '#6F6661',
      inkHint: '#A29A95',
    },
  },
  {
    id: 'pure-white',
    label: '화이트',
    description: '콘텐츠와 사진이 가장 깔끔하게 보이는 흰색 테마',
    previewClassName: 'bg-white border border-[#ECE7E4]',
    tokens: {
      primary: '#D96B7C',
      primaryDeep: '#B94D61',
      primarySoft: '#F7DDE3',
      primaryHalo: 'rgba(217, 107, 124, 0.22)',
      bgApp: '#FFFFFF',
      surface: '#FFFFFF',
      surfaceWarm: '#FAFAFA',
      line: '#ECE7E4',
      lineStrong: '#DDD5D0',
      ink: '#191716',
      inkMuted: '#6F6661',
      inkHint: '#A29A95',
    },
  },
  {
    id: 'paper',
    label: '페이퍼',
    description: '브런치형 글과 사진 카드에 어울리는 차분한 종이톤',
    previewClassName: 'bg-[#FBFAF7]',
    tokens: {
      primary: '#C96C7A',
      primaryDeep: '#A94F5F',
      primarySoft: '#F5DEE1',
      primaryHalo: 'rgba(201, 108, 122, 0.22)',
      bgApp: '#FBFAF7',
      surface: '#FFFFFF',
      surfaceWarm: '#F7F1EA',
      line: '#E9E1D7',
      lineStrong: '#D7C9BA',
      ink: '#1D1A17',
      inkMuted: '#756A61',
      inkHint: '#A89E96',
    },
  },
  {
    id: 'mist-blue',
    label: '미스트 블루',
    description: '날씨 카드와 사진 피드가 산뜻하게 보이는 맑은 테마',
    previewClassName: 'bg-[#F3F7FA]',
    tokens: {
      primary: '#CF6B7E',
      primaryDeep: '#AC5062',
      primarySoft: '#F4DCE3',
      primaryHalo: 'rgba(207, 107, 126, 0.22)',
      bgApp: '#F3F7FA',
      surface: '#FFFFFF',
      surfaceWarm: '#F8FBFD',
      line: '#DDE7EE',
      lineStrong: '#CAD9E2',
      ink: '#172026',
      inkMuted: '#63717A',
      inkHint: '#99A6AE',
    },
  },
  {
    id: 'auto',
    label: '자동 테마',
    description: '나중에 글과 사진 분위기에 맞춰 자동 생성',
    previewClassName: 'bg-gradient-to-br from-[#F8F5F2] via-white to-[#F3F7FA]',
    isAuto: true,
    tokens: {
      primary: '#D96B7C',
      primaryDeep: '#B94D61',
      primarySoft: '#F7DDE3',
      primaryHalo: 'rgba(217, 107, 124, 0.26)',
      bgApp: '#F8F5F2',
      surface: '#FFFFFF',
      surfaceWarm: '#FDF9F6',
      line: '#E8E1DD',
      lineStrong: '#D8CDC7',
      ink: '#191716',
      inkMuted: '#6F6661',
      inkHint: '#A29A95',
    },
  },
];

export const getAppThemePreset = (id?: AppThemeId) =>
  appThemePresets.find((theme) => theme.id === id) ?? appThemePresets[0];

export const createThemeStyle = (theme: AppThemePreset): React.CSSProperties => ({
  '--color-primary': theme.tokens.primary,
  '--color-primary-deep': theme.tokens.primaryDeep,
  '--color-primary-soft': theme.tokens.primarySoft,
  '--color-primary-halo': theme.tokens.primaryHalo,
  '--color-bg-app': theme.tokens.bgApp,
  '--color-surface': theme.tokens.surface,
  '--color-surface-warm': theme.tokens.surfaceWarm,
  '--color-line': theme.tokens.line,
  '--color-line-strong': theme.tokens.lineStrong,
  '--color-ink': theme.tokens.ink,
  '--color-ink-muted': theme.tokens.inkMuted,
  '--color-ink-hint': theme.tokens.inkHint,
} as React.CSSProperties);
